name: docx_template
description: A Docx template engine.
version: 0.4.0
homepage: https://github.com/PavelS0/docx_template_dart
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  archive: ^3.3.0
  xml: ^6.4.2
  collection: ^1.16.0
  path: ^1.8.2
dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.21.3
